spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/scm

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect